export const EcosystemsList = [
  "Ethereum (ETH)",
  "Bitcoin (BTC)",
  "BNB Chain (BNB)",
  "Solana (SOL)",
  "Cardano (ADA)",
  "Polygon (MATIC)",
  "TRON (TRX)",
  "Avalanche (AVAX)",
  "Arbitrum (ARB)",
  "Optimism (OP)",
  "Fantom (FTM)",
  "Tezos (XTZ)",
  "NEAR Protocol (NEAR)",
  "Cosmos (ATOM)",
  "Hedera (HBAR)",
  "Algorand (ALGO)",
  "Celo (CELO)",
  "Harmony (ONE)",
  "Cronos (CRO)",
  "Kava (KAVA)",
  "VeChain (VET)",
  "Zilliqa (ZIL)",
  "Waves (WAVES)",
  "Elrond (EGLD)",
  "Flow (FLOW)",
  "IoTeX (IOTX)",
  "Aurora (AURORA)",
  "Moonbeam (GLMR)",
  "Gnosis (GNO)",
  "xDai Chain",
  "Kusama (KSM)",
  "Polkadot (DOT)",
  "Terra Classic (LUNC)",
  "Terra (LUNA)",
  "Stellar (XLM)",
  "ICON (ICX)",
  "NEO (NEO)",
  "Qtum (QTUM)",
  "EOS (EOS)",
  "Theta (THETA)",
  "Chiliz (CHZ)",
  "Bittorrent (BTT)",
  "OKX Chain (OKT)",
  "Oasis Network (ROSE)",
  "Internet Computer (ICP)",
  "Cortex (CTXC)",
  "Syscoin (SYS)",
  "Syntropy (NOIA)",
  "Telos (TLOS)",
  "Astar (ASTR)",
  "Kadena (KDA)",
  "Shiden Network (SDN)",
  "Secret (SCRT)",
  "Rootstock (RSK)",
  "Lisk (LSK)",
  "Nano (XNO)",
  "Horizen (ZEN)",
  "Decred (DCR)",
  "Zcash (ZEC)",
  "Bitcoin Cash (BCH)",
  "Litecoin (LTC)",
  "Dogecoin (DOGE)",
  "Dash (DASH)",
  "Stacks (STX)",
  "RSK Infrastructure Framework (RIF)",
  "Velas (VLX)",
  "Energi (NRG)",
  "Fusion (FSN)",
  "XinFin (XDC)",
  "Ethereum Classic (ETC)",
  "Ubiq (UBQ)",
  "EthereumPoW (ETHW)",
  "REI Network (REI)",
  "Theta Fuel (TFUEL)",
  "HECO Chain (HT)",
  "Tomochain (TOMO)",
  "BitShares (BTS)",
];

export const FundingStageList = [
  "Pre-Seed",
  "Seed",
  "Private Sale",
  "Pre-ICO",
  "ICO",
  "IDO",
  "STO",
  "Public Sale",
  "Post ICO Sale",
  "Series A, B, C",
  "Grants",
];

export const RequestTypeList = [
  "Technical Collaboration",
  "Funding",
  "Listing",
  "Marketing",
  "Integrations",
  "Community Building",
  "Explore",
];

export const ProfileStatusList = ["Verified", "Unverified"];

export const LocationList = ["All Countries", "Remote", "Global"];

export const PartnershipInterestList = [
  "AI & Big Data",
  "	 Art	",
  "	 Asset Management	",
  "	 Asset-backed Tokens	",
  "	 Augmented Reality	",
  "	 Automated Market Maker (AMM)	",
  "	 BNB Chain Ecosystem	",
  "	 Centralized Exchange (CEX)	",
  "	 Charity	",
  "	 Communication	",
  "	Content Creation	",
  "	 Crowdfunding	",
  " DAO	",
  "	 Dapp	",
  "	 Decentralized Exchange (DEX)	",
  "	 DeFi	",
  "	 Derivatives	",
  "	 Dex Aggregator	",
  "	 E-Commerce	",
  "	 Education	",
  "	 Energy	",
  "	 Entertainment	",
  "	 Esports	",
  "	 Ethereum Ecosystem	",
  "	 Exchange-based Tokens	",
  "	 Fan Token	",
  "	 Farming-as-a-Service (FaaS)	",
  "	 File Sharing	",
  "	 Gaming	",
  "	 Governance	",
  "	 Gambling	",
  "	 Healthcare	",
  "	 Insurance	",
  "	 Interoperability	",
  "	 IoT	",
  "	 Launchpad	",
  "	 Layer 1 (L1)	",
  "	 Layer 2 (L2)	",
  "	 Legal	",
  "	 Lending & Borrowing	",
  "	 Loyalty	",
  "	 Manufacturing	",
  "	 Marketplaces	",
  "	 Marketing	",
  "	 Media	",
  "	 Memes	",
  "	 Metaverse	",
  "	 Mining	",
  "	 Mobile	",
  "	 Music	",
  "	 NFT	",
  "	 Oracles	",
  "	 Polkadot Ecosystem	",
  "	 Privacy	",
  "	 Real Estate	",
  "	 Rebase Tokens	",
  "	 Retail	",
  "	 RWA (Real World Assets)	",
  "	 Sharing Economy	",
  "	 Smart Contract Platform	",
  "	 Social Money	",
  "	 Social	",
  "	 Sports	",
  "	 Stablecoins	",
  "	 Storage	",
  "	 Supply Chain & Logistics	",
  "	 Synthetic Issuer	",
  "	 Technology & Science	",
  "	 Tokenized Bitcoin	",
  "	 Trading	",
  "	 Virtual Goods	",
  "	 VR/AR	",
  "	 Wallet	",
  "	 Web3	",
  "Yield Aggregator",
];
export const CategoryList = [
  "AI & Big Data",
  "Art",
  "Asset Management",
  "Asset-backed Tokens	",
  "Augmented Reality",
  "Automated Market Maker(AMM)",
  "BNB Chain Ecosystem	",
  "Centralized Exchange (CEX)	",
  "Charity",
  "	 Communication	",
  "	Content Creation	",
  "	 Crowdfunding	",
  " DAO	",
  "	 Dapp	",
  "	 Decentralized Exchange (DEX)	",
  "	 DeFi	",
  "	 Derivatives	",
  "	 Dex Aggregator	",
  "	 E-Commerce	",
  "	 Education	",
  "	 Energy	",
  "	 Entertainment	",
  "	 Esports	",
  "	 Ethereum Ecosystem	",
  "	 Exchange-based Tokens	",
  "	 Fan Token	",
  "	 Farming-as-a-Service (FaaS)	",
  "	 File Sharing	",
  "	 Gaming	",
  "	 Governance	",
  "	 Gambling	",
  "	 Healthcare	",
  "	 Insurance	",
  "	 Interoperability	",
  "	 IoT	",
  "	 Launchpad	",
  "	 Layer 1 (L1)	",
  "	 Layer 2 (L2)	",
  "	 Legal	",
  "	 Lending & Borrowing	",
  "	 Loyalty	",
  "	 Manufacturing	",
  "	 Marketplaces	",
  "	 Marketing	",
  "	 Media	",
  "	 Memes	",
  "	 Metaverse	",
  "	 Mining	",
  "	 Mobile	",
  "	 Music	",
  "	 NFT	",
  "	 Oracles	",
  "	 Polkadot Ecosystem	",
  "	 Privacy	",
  "	 Real Estate	",
  "	 Rebase Tokens	",
  "	 Retail	",
  "	 RWA (Real World Assets)	",
  "	 Sharing Economy	",
  "	 Smart Contract Platform	",
  "	 Social Money	",
  "	 Social	",
  "	 Sports	",
  "	 Stablecoins	",
  "	 Storage	",
  "	 Supply Chain & Logistics	",
  "	 Synthetic Issuer	",
  "	 Technology & Science	",
  "	 Tokenized Bitcoin	",
  "	 Trading	",
  "	 Virtual Goods	",
  "	 VR/AR	",
  "	 Wallet	",
  "	 Web3	",
  "Yield Aggregator",
];
